#!/bin/bash

# sudo apt install xclip zenity

if [[ $(xclip -o clipboard | tail -c 1) == '' ]]; then
  zenity --notification --text="Lines in clipboard: $(xclip -o clipboard | wc -l)"
else
  zenity --notification --text="Lines in clipboard: $((`xclip -o sel clip | wc -l`+1))"
fi

